# This workflow runs `flutter analyze` and `flutter test` for every pull request.

name: Run analyze and tests
on: pull_request
jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Install dependencies /example
        run: flutter pub get
        working-directory: example
      - name: Build
        run: flutter build aot --release -t lib/main_production.dart
      - name: Run analyzer
        run: flutter analyze
      - name: Run analyzer /example
        run: flutter analyze
        working-directory: example
      - name: Run tests
        run: flutter test
      - name: Run tests /example
        run: flutter test
        working-directory: example